### ISSUE TITLE
新建数据线时，启动Topology报错

### ISSUE THREAD

**Issue by yiyuqiuchi** [BriData/DBus#11]
Traceback (most recent call last):
  File "/data/dbus/apache-storm-1.0.1//bin/storm.py", line 766, in <module>
    main()
  File "/data/dbus/apache-storm-1.0.1//bin/storm.py", line 763, in main
    (COMMANDS.get(COMMAND, unknown_command))(*ARGS)
  File "/data/dbus/apache-storm-1.0.1//bin/storm.py", line 234, in jar
    transform_class = confvalue("client.jartransformer.class", [CLUSTER_CONF_DIR])
  File "/data/dbus/apache-storm-1.0.1//bin/storm.py", line 144, in confvalue
    p = sub.Popen(command, stdout=sub.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

不知是哪里有问题？

**Comment by yiyuqiuchi** [comment]
已解决

**Comment by lynchlee** [comment]
👍  捂脸。解决方案说一下哇。以后碰到的同学也可以帮助到呢。

**Comment by zhanguolin** [comment]
麻烦说下解决方案 ，我现在遇到这个问题了，我是通过日志文件里面的指令然后再服务器里面执行，请问您是怎么处理的

**Comment by struggle3014** [comment]
问题原因：
由于环境变量导致。问题可以参考：https://stackoverflow.com/questions/31362113/python-oserror-errno-2-no-such-file-or-directory-on-subprocess-popen
解决方案：
将安装 dbus 用户的 ~/.bashrc 以及 /etc/bashrc 添加相应的环境配置。
对于以上配置文件的详细描述可见：https://blog.csdn.net/u010842515/article/details/51593936
