### ISSUE TITLE
使用 dbus 0.4.0，启动 dbus-heartbeat 报错

### ISSUE THREAD

**Issue by struggle3014** [BriData/DBus#19]
[pool-5-thread-1] ERROR: 2019/03/26 09:33:15.481 GlobalControlKafkaConsumerEvent 144 - [Global-Control-kafka-Consumer-event] topic: global_ctr
l_topic ,value:null
java.lang.NullPointerException
	at com.creditease.dbus.heartbeat.event.impl.GlobalControlKafkaConsumerEvent.run(GlobalControlKafkaConsumerEvent.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by struggle3014** [comment]
问题已解决，造成该错误的原因是 producer.properties 配置文件中的 zk 地址有误。
