### ISSUE TITLE
Router topo超时报警

### ISSUE THREAD

**Issue by daxiaCC** [BriData/DBus#40]
数据量在1千左右的时候就会超时延迟

![image](https://user-images.githubusercontent.com/33630060/69772684-9ee40b80-11cb-11ea-8ff5-5efda3422330.png)

**Comment by daxiaCC** [comment]
您好:
  报警类型:超时报警
  项目:ph_test
  拓扑:ph_test_topo_01
  数据源:ph_test
  数据库:testdb
  报警时间:2019-11-28 02:32:58.165
  报警环境:[测试]
以下表格中table发生报警,请及时处理.
Zk Path	Alarm Count	Time Out	Time Out Count
/DLake/HeartBeat/ProjectMonitor/ph_test/ph_test_topo_01/ph_test.testdb.test_01	1	10分钟14秒	1

**Comment by star-brilliant** [comment]
单个router不要消费太多topic，可以修改consumer一次读取数量，或者加大worker内存

**Comment by daxiaCC** [comment]
router只消费了一个topic，问题出在canal一只报错，执行几分钟后就一直抛异常，但是数据还是可以采集到的，数据延迟应该在这：
2019-11-29 00:00:12.350 [New I/O server worker #1-3] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wro
ng with channel:[id: 0x15024850, /10.10.0.210:51166 => /10.10.0.85:10000], exception=java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
