### ISSUE TITLE
com.jcraft.jsch.JSchException: Auth fail

### ISSUE THREAD

**Issue by 15521529438** [BriData/DBus#75]
加载config.properties配置文件中...
nginx地址检测通过
测试数据库连通性...
Tue Oct 20 09:05:42 CST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
数据库连通性测试通过
kafka检测通过
influxdb地址检测通过
测试ZK连通性...
[main] INFO org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.8--1, built on 02/06/2016 03:18 GMT
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=centos151
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_262
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=../lib/keeper-auto-deploy-0.6.1-jar-with-dependencies.jar
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=3.10.0-957.el7.x86_64
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/app/dbus/dbus-keeper/bin
[main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.186.151:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@3159c4b8
[main-SendThread(192.168.186.151:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.186.151/192.168.186.151:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(192.168.186.151:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.186.151/192.168.186.151:2181, initiating session
[main-SendThread(192.168.186.151:2181)] INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.186.151/192.168.186.151:2181, sessionid = 0x175403e4296001c, negotiated timeout = 40000
[main-EventThread] INFO org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
ZK连通性测试通过
[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x175403e4296001c closed
验证密钥是否存在...
~/.ssh/id_rsa密钥文件存在
[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x175403e4296001c
com.jcraft.jsch.JSchException: Auth fail
java.lang.RuntimeException: com.jcraft.jsch.JSchException: Auth fail
        at com.creditease.dbus.auto.deploy.DBusKeeperInitAll.checkSSH(DBusKeeperInitAll.java:604)
        at com.creditease.dbus.auto.deploy.DBusKeeperInitAll.checkSSH(DBusKeeperInitAll.java:86)
        at com.creditease.dbus.auto.deploy.DBusKeeperInitAll.main(DBusKeeperInitAll.java:54)
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at com.creditease.dbus.auto.deploy.DBusKeeperInitAll.checkSSH(DBusKeeperInitAll.java:589)
        ... 2 more

**Comment by 15521529438** [comment]
解决了，这个是单机部署的，所以出这个问题是自己调用自己出问题的，把自己的公钥放进authorized_keys就可以了
